spring:
  application:
    name: Api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: AUTH-SERVICE
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth,/api/v1/auth/**
            - id: project-service
              uri: lb://PROJECT-SERVICE
              predicates:
                - Path=/api/v1/projects,/api/v1/projects/**
            - id: task-service
              uri: lb://TASK-SERVICE
              predicates:
                - Path=/api/v1/tasks,/api/v1/tasks/**
            - id: sprint-service
              uri: lb://SPRINT-SERVICE
              predicates:
                - Path=/api/v1/sprints,/api/v1/sprints/**
            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/v1/notifications,/api/v1/notifications/**

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
